# .readthedocs.yml
# Read the Docs configuration file

# Details
# - https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
      - method: pip
        path: .
        extra_requirements:
          - docs

sphinx:
  configuration: doc/conf.py
  builder: html
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
#formats:
#  - pdf
