---
name: "Tests: DynamoDB"

on:
  pull_request:
    paths:
    - '.github/workflows/dynamodb.yml'
    - 'cratedb_toolkit/io/dynamodb/**'
    - 'tests/io/dynamodb/**'
    - 'pyproject.toml'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/dynamodb.yml'
    - 'cratedb_toolkit/io/dynamodb/**'
    - 'tests/io/dynamodb/**'
    - 'pyproject.toml'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run the job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [
          "3.10",
          "3.13",
        ]
        localstack-version: ["4.5"]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      LOCALSTACK_VERSION: ${{ matrix.localstack-version }}
      UV_SYSTEM_PYTHON: true
      # Do not tear down Testcontainers
      TC_KEEPALIVE: true

    name: "
    Python ${{ matrix.python-version }}, 
    LocalStack ${{ matrix.localstack-version }}, 
    OS ${{ matrix.os }}
    "
    steps:

    - name: Acquire sources
      uses: actions/checkout@v5

    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        cache-dependency-glob: |
          pyproject.toml
        cache-suffix: ${{ matrix.python-version }}
        enable-cache: true
        version: "latest"

    - name: Set up project
      run: |

        # Install package in editable mode.
        uv pip install --editable=.[dynamodb,kinesis,test]

    - name: Run software tests
      run: |
        pytest -m dynamodb

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
        flags: dynamodb
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
