---
name: "Tests: Kinesis"

on:
  pull_request:
    paths:
    - '.github/workflows/kinesis.yml'
    - 'cratedb_toolkit/io/kinesis/**'
    - 'cratedb_toolkit/testing/testcontainers/localstack.py'
    - 'cratedb_toolkit/testing/testcontainers/util.py'
    - 'tests/io/kinesis/**'
    - 'pyproject.toml'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/kinesis.yml'
    - 'cratedb_toolkit/io/kinesis/**'
    - 'cratedb_toolkit/testing/testcontainers/localstack.py'
    - 'cratedb_toolkit/testing/testcontainers/util.py'
    - 'tests/io/kinesis/**'
    - 'pyproject.toml'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run the job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [
          "3.10",
          # TODO: Integration tests became flaky again. Let's investigate later.
          #       kinesis.exceptions.StreamDoesNotExist: Stream 'testdrive' does not exist
          # "3.13",
        ]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      # Do not tear down Testcontainers
      TC_KEEPALIVE: true

    # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
    services:
      cratedb:
        image: crate/crate:nightly
        ports:
          - 4200:4200
          - 5432:5432

    name: "
    Kinesis:
    Python ${{ matrix.python-version }} on OS ${{ matrix.os }}"
    steps:

    - name: Acquire sources
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: 'true'
        cache-suffix: ${{ matrix.python-version }}
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Set up project
      run: |

        # Install package in editable mode.
        uv pip install --editable=.[kinesis,test]

    - name: Run software tests
      run: |
        pytest -m kinesis

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
        flags: kinesis
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
